name: fmv
description: A cross-platform media gallery and metadata explorer app.
publish_to: none

version: 1.14.9+173

environment:
  # this project bundles Flutter SDK via `flutter_wrapper`
  # cf https://github.com/passsy/flutter_wrapper
  flutter: ">=3.44.0"
  sdk: ">=3.12.0 <4.0.0"

platforms:
  android:
  ios:
  linux:

workspace:
  - plugins/fmv_magnifier
  - plugins/fmv_map
  - plugins/fmv_model
  - plugins/fmv_report
  - plugins/fmv_report_console
  - plugins/fmv_screen_state
  - plugins/fmv_services
  - plugins/fmv_services_none
  - plugins/fmv_ui
  - plugins/fmv_utils
  - plugins/fmv_video
  - plugins/fmv_video_exo
  - plugins/fmv_video_mpv
  - plugins/fmv_staggered_animations
  - plugins/fmv_localizations_plus
  - plugins/fmv_expansion_tile_card
  - plugins/fmv_panorama
  - plugins/fmv_streams_channel
  - plugins/fmv_charts/community_charts_flutter

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  fmv_magnifier:
    path: plugins/fmv_magnifier
  fmv_map:
    path: plugins/fmv_map
  fmv_model:
    path: plugins/fmv_model
  fmv_report:
    path: plugins/fmv_report
  fmv_report_platform:
    path: plugins/fmv_report_console
  fmv_screen_state:
    path: plugins/fmv_screen_state
  fmv_services:
    path: plugins/fmv_services
  fmv_services_platform:
    path: plugins/fmv_services_none
  fmv_video:
    path: plugins/fmv_video
  #  fmv_video_exo:
  #    path: plugins/fmv_video_exo
  fmv_video_mpv:
    path: plugins/fmv_video_mpv
  fmv_ui:
    path: plugins/fmv_ui
  fmv_utils:
    path: plugins/fmv_utils
  collection:
  fmv_charts:
    path: plugins/fmv_charts/community_charts_flutter
  connectivity_plus: ^6.1.0
  country_code:
  crypto:
  csv:
  decorated_icon:
  device_info_plus: ^11.3.0
  dlna_dart:
  dynamic_color:
  equatable:
  event_bus:
  file_picker: ^11.0.0
  fmv_expansion_tile_card:
    path: plugins/fmv_expansion_tile_card
  flex_color_picker:
  floating:
    git:
      url: https://github.com/deckerst/floating.git
      ref: agp9
  fluster:
  flutter_displaymode:
  flutter_highlight:
  fmv_localizations_plus:
    path: plugins/fmv_localizations_plus
  flutter_map:
  flutter_markdown_plus:
  fmv_staggered_animations:
    path: plugins/fmv_staggered_animations
  get_it:
  gpx:
  highlight:
  http:
  image:
  intl:
  intl4x: 1.0.0-alpha.2
  latlong2:
  leak_tracker:
  local_auth:
  material_color_utilities:
  flutter_material_design_icons:
  material_symbols_icons:
  network_info_plus:
  overlay_support: ^2.1.0
  package_info_plus:
  fmv_panorama:
    path: plugins/fmv_panorama
  path:
  path_provider:
  pattern_lock:
  pdf:
  percent_indicator: ^4.2.3
  permission_handler:
  pin_code_fields:
  printing:
  proj4dart:
  provider:
  screen_brightness:
  shamsi_date:
  share_plus:
  shared_preferences:
  shelf:
  smooth_page_indicator:
  sqflite:
  sqflite_common_ffi:
  stack_trace:
  fmv_streams_channel:
    path: plugins/fmv_streams_channel
  synchronized:
  url_launcher:
  # `vector_map_tiles` v10.0.0-beta API is unclear to provide sprites
  vector_map_tiles: ^9.0.0-beta
  vector_math:
  vector_tile_renderer:
  volume_controller:
  video_thumbnail:
  xml:

dependency_overrides:
  media_kit_video:
    git:
      url: https://github.com/deckerst/media-kit.git
      path: media_kit_video
      ref: video_controller_disposal

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  shared_preferences_platform_interface:
  test:

flutter:
  assets:
    - assets/
  generate: true
  uses-material-design: true
