blank_issues_enabled: false
contact_links:
  - name: I have a question
    url: https://github.com/naipingzai/Flutter_MediaManager/discussions
    about: Feel free to ask questions in the Discussions.